### PR TITLE
Authorization integrational testing ended

### PR DESCRIPTION
**Pull request by Karol2846**
Test's for Authorization created

### CODE REVIEW

**Review by MajewskiOliwier — CHANGES_REQUESTED** [review]
This is missing the method for checking incorrect login data

**Comment by MajewskiOliwier** [comment]
> This is missing the method for checking incorrect login data

Beside you will need to rebase to get exception handling

**Review by TomaszMarek — APPROVED** [review]

**Comment by Karol2846** [comment]
Okey, method for invalid data created - now Iill wait to exception handlers

**Comment by Karol-Mac** [comment]
Okey, method for invalid data created - now Iill wait to exception handlers

**Review by TomaszMarek — APPROVED** [review]

**Comment by MajewskiOliwier** [comment]
> Okey, method for invalid data created - now Iill wait to exception handlers

There should be an exception handler on master RN

**Pull request closed without merging**
